### ISSUE TITLE
Not relevant name of the module

### ISSUE THREAD

**Issue by yarikos** [martintajur/node-mysql-activerecord#11]
Actually a functionality in this module  isn't could be called 'Active Record'. 

In Active Record every table in the database is represented by the separate class in the code, and any instance of this class represents an one record of appropriate table.

The using of this module is sort of using helpers for building SQL queries and running them (I don't know the name of a pattern for this, if one exists).

While an example of mapping as Active Record would be like this:

```javascript
// Defining the model
Person = db.ActiveRecord.extend({
	fields :[name, email, phone, city],
	tableName: 'people'
});


// Using it for creating records
var newPerson = new Person({
	name : 'John',
	email: 'johnsmith@example.com',	
});

newPerson.save(function() {
	// now the table is updated
});


// Using the model for selecting and changing
Person.find({
	city: 'London'
}, doSomeProcessingAndUpdatePhone);


function doSomeProcessingAndUpdatePhone(people) {
	people.each(function(person) {
		var phone = anotherModule.getPhoneByPersonId(person.id);
		person.phone = phone;

		anotherModule.doSomeProcessing(person);

		// at this moment changes aren't stored in database

		person.save(function() {
			// now the record in the table 'people' is updated                        
		});
	});
}
````

That's why, the module name without "activerecord" would be more relevant.

**Comment by martintajur** [comment]
+1 to what Kyle said. Closing this down, not going to do a huge rename right now and I suspect Kyle's fork (which he had actually implemented some time ago) is worth checking out for sure.
