### ISSUE TITLE
This project alive?

### ISSUE THREAD

**Issue by Tuch** [martintajur/node-mysql-activerecord#25]
please tell, this project is still alive?

**Comment by kylefarris** [comment]
Hi Tuch, I'm not sure if there's going to be much more work done on this module, but, I've forked it and made SIGNIFICANT enhancements to it while keeping, basically, the same API. Check it out here: https://github.com/kylefarris/node-querybuilder or install it using `npm i --save node-querybuilder`.

You can think of my fork as the "new" version of this module but one that is so much different that it didn't make sense to do a PR back into this one. @martintajur was definitely credited, though.

**Comment by martintajur** [comment]
@kylefarris Kyle seems to have done an excellent job with this fork.

**Comment by martintajur** [comment]
@Tuch For now, I am not actively adding new functionality to this project but I think Kyle's fork is definitely worth checking out. However my project is used in production in variety of places and it definitely solves the needs.

**Comment by Tuch** [comment]
ok :(, thx for your work man

**Comment by martintajur** [comment]
@Tuch Which functionality were you missing out on specifically btw? Or is it more generally "are you still working on it?" kind of question?

**Comment by Tuch** [comment]
Yeah, i wanted to use your library in backend of my project, but now i worked for frontend and i dont work for backend now..

**Comment by martintajur** [comment]
Ok. No worries and sorry for being slow with the response. Nevertheless good luck with your project!
